### ISSUE TITLE
No Service called "Bluetooth Audio Gateway Service" found

### ISSUE THREAD

**Issue by C-Noob404** [helldivers2fixes/HellbombScript#18]
Hello,

first of all, thank you for this awesome script. Unfortunately I'm always getting the following Error:

` Get-Service : Es kann kein Dienst mit dem Dienstnamen "Bluetooth Audio Gateway Service" gefunden werden.
In Zeile:275 Zeichen:10
     if ((Get-Service -Name 'Bluetooth Audio Gateway Service').Status  ...
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        CategoryInfo          : ObjectNotFound: (Bluetooth Audio Gateway Service:String) [Get-Service], ServiceCommandException    FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand`

Does anyone have an idea what I can do?

Thank you very much.

**Comment by C-Noob404** [comment]
I fixed it. Just replace "Bluetooth Audio Gateway Service" with "BTAGService" in the script and it works.

**Comment by helldivers2fixes** [comment]
> I fixed it. Just replace "Bluetooth Audio Gateway Service" with "BTAGService" in the script and it works.

Thank you for opening this issue! Do you mind mentioning what OS version this was? I tried to re-produce on Windows 11 and wasn't able to. Did this occur on Windows 10?

Regardless, I should make all the service names consistent, so thank you for pointing that out!
