### ISSUE TITLE
Would Omen Gaming Hub be considered problematic software, like Razer Cortex?

### ISSUE THREAD

**Issue by FairwellNoob** [helldivers2fixes/HellbombScript#26]
https://apps.microsoft.com/detail/9nqdw009t0t5?amp%3Bgl=US&hl=en-us&gl=EG
It's similar to it with "memory boosting" and CPU features, but I use it because it contains drivers and coded routines to control laptop hardware functions, like keyboard lighting, drivers that manage voltage to laptop components, fan management, etc.
I am looking for alternatives such as https://omenmon.github.io/ but I am not sure if it were to cause issues aswell

**Comment by helldivers2fixes** [comment]
> https://apps.microsoft.com/detail/9nqdw009t0t5?amp%3Bgl=US&hl=en-us&gl=EG It's similar to it with "memory boosting" and CPU features, but I use it because it contains drivers and coded routines to control laptop hardware functions, like keyboard lighting, drivers that manage voltage to laptop components, fan management, etc. I am looking for alternatives such as https://omenmon.github.io/ but I am not sure if it were to cause issues aswell

That's a great question! I'm not sure if Omen Gaming Hub is an issue or not. Most of what you mentioned shouldn't be an issue if the app is written well. But "memory-boosting" and 'optimizations' (including network optimizers) may cause issues.
Are you having issues with the game? FYI, currently the SPEAR causes crashes. I'd try only disabling any 'optimizations' that the app offers that mess with CPU threading or mess with memory.

**Comment by FairwellNoob** [comment]
> > https://apps.microsoft.com/detail/9nqdw009t0t5?amp%3Bgl=US&hl=en-us&gl=EG It's similar to it with "memory boosting" and CPU features, but I use it because it contains drivers and coded routines to control laptop hardware functions, like keyboard lighting, drivers that manage voltage to laptop components, fan management, etc. I am looking for alternatives such as https://omenmon.github.io/ but I am not sure if it were to cause issues aswell
> 
> That's a great question! I'm not sure if Omen Gaming Hub is an issue or not. Most of what you mentioned shouldn't be an issue if the app is written well. But "memory-boosting" and 'optimizations' (including network optimizers) may cause issues. Are you having issues with the game? FYI, currently the SPEAR causes crashes. I'd try only disabling any 'optimizations' that the app offers that mess with CPU threading or mess with memory.

Issues as in performance, crashes, or both? I'm not sure if I can reliably give a statement on optimization & performance as that is iffy even on the most high-end systems, but I have not experienced frequent crashes while using it

**Comment by helldivers2fixes** [comment]
> Issues as in performance, crashes, or both? I'm not sure if I can reliably give a statement on optimization & performance as that is iffy even on the most high-end systems, but I have not experienced frequent crashes while using it

Sorry, somehow missed that you replied. I meant either one. I haven't seen others report the same issues, which is why I was asking. (Plenty of Omen users). But it may be an issue.

**Comment by helldivers2fixes** [comment]
Closing this as I don't have any data supporting that this is an issue, and plenty of data supporting that this program doesn't cause problems. But, maybe it'll need to be opened at a later date.
