### ISSUE TITLE
Memory multi-channel detection not working correctly.

### ISSUE THREAD

**Issue by Cantejito** [helldivers2fixes/HellbombScript#77]
HWiNFO v8.14 screenshot for proof.
![Screenshot_1](https://github.com/user-attachments/assets/a82b04e7-61d3-4a2a-b55e-834174ce1fd0)

**Comment by helldivers2fixes** [comment]
Thank you for opening this issue!
This should be addressed in #76 Have you happened to copy and paste the code to PowerShell or Terminal and see if it works correctly now by chance?
https://github.com/helldivers2fixes/HellbombScript/blob/9cdb16d8a4f2af49f938249b73178e19fb25d570/Hellbomb%20Script.ps1

**Comment by Cantejito** [comment]
I tried again both directly on PowerShell and last .exe release, and now seems to work as intended.

![Screenshot_1](https://github.com/user-attachments/assets/d141a135-c06a-4279-9bb8-999110073736)
